### PR TITLE
Add openbook support, need blockstream PR merged

### PR DESCRIPTION
**Pull request by atulsriv**
Blocked by https://github.com/bloXroute-Labs/solana-trader-client-ts/pull/35

### CODE REVIEW

**Review by aspin — CHANGES_REQUESTED** [review]
http provider needs to be updated to add `project=` to several endpoints

example: https://github.com/bloXroute-Labs/solana-trader-client-go/pull/77/files#diff-39f5c63d71a9df557ad9cf95d2cb3d610659c681fcdc600e535add1972e970ddR74

**Comment by aspin** [comment]
BTW how on earth is the integration test passing here? there's no way that should be possible. doesn't look like we're setting the return code when an example fails maybe?

**Comment by atulsriv** [comment]
> BTW how on earth is the integration test passing here? there's no way that should be possible. doesn't look like we're setting the return code when an example fails maybe?

exit codes are all set to 0 so that is why it's passing. I did some testing and changed them to appropriate other error codes but there are some examples that need some work to get passing. Do you want that to be apart of this PR?

**Comment by aspin** [comment]
> > BTW how on earth is the integration test passing here? there's no way that should be possible. doesn't look like we're setting the return code when an example fails maybe?
> 
> exit codes are all set to 0 so that is why it's passing. I did some testing and changed them to appropriate other error codes but there are some examples that need some work to get passing. Do you want that to be apart of this PR?

separate PR is fine

**Review by aspin — APPROVED** [review]

**Pull request merged**
